/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 scene.gltf -t
Author: drei.lu (https://sketchfab.com/drei.lu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-exploration-wlp-series-8-91964c1ce1a34c3985b6257441efa500
Title: Space exploration [WLP series #8]
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    planet001_1: THREE.Mesh;
    planet001_2: THREE.Mesh;
  };
  materials: {
    scene: THREE.MeshStandardMaterial;
  };
};

export function Space(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./Assets/background/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-0.003, 0.024, -6.331]}
          rotation={[0.238, -0.545, 0.562]}
          scale={7}
        >
          <mesh
            geometry={nodes.planet001_1.geometry}
            material={materials.scene}
          />
          <mesh
            geometry={nodes.planet001_2.geometry}
            material={materials.scene}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./Assets/background/scene.gltf");
