/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 scene.gltf -t
Author: Architecture_Interior (https://sketchfab.com/architecture_interior)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sky-box-8k-night-forest-scene-with-aurora-sky-a626c2f3eda14177b07f9c345a17df60
Title: SKY BOX 8K - NIGHT FOREST SCENE WITH AURORA SKY
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Sphere001_Material_#26_0']: THREE.Mesh
  }
  materials: {
    Material_26: THREE.MeshStandardMaterial
  }
}

export function NightSky(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Assets/nightSky/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <mesh geometry={nodes['Sphere001_Material_#26_0'].geometry} material={materials.Material_26} position={[0.309, 60.152, -4.774]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('./Assets/nightSky/scene.gltf');
